[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT/Apache-2.0"
edition = "2024"
repository = "https://github.com/paritytech/revive-differential-testing.git"
rust-version = "1.91.0"

[workspace.dependencies]
revive-dt-common = { version = "0.1.0", path = "crates/common" }
revive-dt-compiler = { version = "0.1.0", path = "crates/compiler" }
revive-dt-config = { version = "0.1.0", path = "crates/config" }
revive-dt-format = { version = "0.1.0", path = "crates/format" }
revive-dt-node = { version = "0.1.0", path = "crates/node" }
revive-dt-node-interaction = { version = "0.1.0", path = "crates/node-interaction" }
revive-dt-report = { version = "0.1.0", path = "crates/report" }
revive-dt-solc-binaries = { version = "0.1.0", path = "crates/solc-binaries" }
revive-dt-proc-macros = { version = "0.1.0", path = "crates/proc-macros" }
revive-dt-profiler = { version = "0.1.0", path = "crates/profiler" }
revive-dt-runtime-builder = { version = "0.1.0", path = "crates/runtime-builder" }

alloy = { version = "1.4.1", features = [
    "full",
    "genesis",
    "json-rpc",
    "rand",
] }
ansi_term = "0.12.1"
base64 = "0.22"
bitflags = { version = "2.13.0", features = ["serde"] }
cargo_metadata = "0.23.1"
flate2 = "1.0"
anyhow = "1.0"
bson = { version = "2.15.0" }
cacache = { version = "13.1.0" }
clap = { version = "4", features = ["derive", "wrap_help"] }
dashmap = { version = "6.1.0" }
foundry-compilers-artifacts = { version = "0.18.0" }
futures = { version = "0.3.31" }
git2 = { version = "0.21.0", default-features = false, features = ["https"] }
hex = "0.4.3"
quote = "1.0.44"
regex = "1"
rustc-demangle = "0.1.28"
moka = "0.12.10"
polkavm-linker = "0.36.0"
proc-macro2 = "1.0.106"
reqwest = { version = "0.12.15", features = ["json"] }
once_cell = "1.21"
schemars = { version = "1.0.4", features = ["semver1", "indexmap2"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = [
    "arbitrary_precision",
    "std",
    "unbounded_depth",
    "preserve_order",
] }
serde_with = { version = "3.14.0", features = ["hex"] }
sha2 = { version = "0.10.9" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438", features = ["serde"] }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-externalities = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-wasm-interface = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438", features = ["wasmtime"] }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
cumulus-primitives-proof-size-hostfunction = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
strum = { version = "0.27.2", features = ["derive"] }
syn = { version = "2.0.117", features = ["full"] }
subxt = { version = "0.43.0", features = ["reconnecting-rpc-client"] }
temp-dir = { version = "0.1.16" }
tempfile = "3.3"
toml = "0.8"
tokio = { version = "1.47.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "process",
    "rt",
] }
tokio-stream = { version = "0.1.18", default-features = false, features = [
    "sync",
] }
tower = { version = "0.5.2", features = ["limit"] }
tracing = { version = "0.1.41" }
tracing-appender = { version = "0.2.3" }
tracing-subscriber = { version = "=0.3.19", default-features = false, features = [
    "fmt",
    "json",
    "env-filter",
] }
wasm-encoder = { version = "0.259.0", features = ["wasmparser"] }
wasmparser = "0.259.0"
wat = "1.259.0"
console-subscriber = { version = "0.5.0" }
indexmap = { version = "2.10.0", default-features = false }
itertools = { version = "0.14.0" }
derive_more = { version = "2.1.1" }

# revive compiler
revive-solc-json-interface = { version = "1.1.0" }
revive-common = { version = "1.1.0" }

zombienet-sdk = { version = "0.4.14" }
pallet-revive = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438", default-features = true }
pallet-revive-types = { git = "https://github.com/paritytech/polkadot-sdk", rev = "cde8a924504c99e768940bf6b600716725c3c438" }
revm-bytecode = { version = "6.2.2", default-features = false, features = ["std"] }
parity-scale-codec = { version = "3.7.5", features = ["derive"] }

[profile.bench]
inherits = "release"
codegen-units = 1
lto = true

[profile.production]
inherits = "release"
codegen-units = 1
lto = true

[profile.profiling]
inherits = "release"
codegen-units = 1
debug = "full"
lto = true
split-debuginfo = "packed"
strip = "none"

[workspace.lints.clippy]
