mod context;
mod runner_event;

/// Generates a CLI-integrated configuration system from a declarative module definition.
///
/// # Motivation
///
/// The retester tool has many subcommands (`test`, `benchmark`, `export-genesis`, etc.), each
/// requiring a different subset of configuration parameters (compilers, nodes, wallets, etc.).
/// This macro keeps the `Context` enum and its subcommand definitions in sync. You declare the
/// subcommands and their configurations, and the shared CLI structure is generated.
///
/// # Usage
///
/// The macro is applied to a module containing struct definitions annotated with either
/// `#[subcommand]` or `#[configuration]`:
///
/// ```rust,ignore
/// #[revive_dt_proc_macros::context(
///     context_type_ident = "Context",
///     default_derives = "Clone, Debug, Parser, Serialize, Deserialize"
/// )]
/// #[command(name = "retester")]
/// mod context {
///     use super::*;
///
///     #[subcommand]
///     pub struct Test {
///         pub solc: SolcConfiguration,
///         pub wallet: WalletConfiguration,
///     }
///
///     #[subcommand]
///     pub struct Benchmark {
///         pub solc: SolcConfiguration,
///     }
///
///     #[subcommand]
///     pub struct ExportJsonSchema;
///
///     #[configuration(key = "solc")]
///     pub struct SolcConfiguration {
///         #[clap(default_value = "0.8.29")]
///         pub version: Version,
///     }
///
///     #[configuration(key = "wallet")]
///     pub struct WalletConfiguration {
///         #[clap(default_value_t = 100_000)]
///         pub additional_keys: usize,
///     }
///
///     impl Test {
///         pub fn custom_method(&self) { /* ... */ }
///     }
///
///     impl Default for Test {
///         fn default() -> Self {
///             Self::parse_from(["test", "--test", "."])
///         }
///     }
/// }
/// ```
///
/// # Macro arguments
///
/// | Argument | Default | Description |
/// |----------|---------|-------------|
/// | `context_type_ident` | `"Context"` | The name of the generated enum type. |
/// | `default_derives` | *(none)* | Comma-separated derive macros applied to all generated types. |
///
/// # Item annotations
///
/// ## `#[subcommand]`
///
/// Marks a struct as a CLI subcommand (a variant of the generated `Context` enum). Each field
/// must be a type annotated with `#[configuration]`. Fields are automatically flattened into the
/// CLI via `#[clap(flatten)]`.
///
/// ## `#[configuration]` / `#[configuration(key = "...")]`
///
/// Marks a struct as a configuration group. The optional `key` argument prefixes all fields in
/// the CLI. For example, `#[configuration(key = "solc")]` on a struct with a `version` field
/// produces the CLI flag `--solc.version`. A `help_heading` is automatically derived from the
/// key (e.g. `"solc"` becomes `"Solc Configuration"`), or can be specified explicitly.
///
/// # What is generated
///
/// Given the example above, the macro produces the following (simplified):
///
/// ## 1. Context enum
///
/// A sum type with one boxed variant per subcommand:
///
/// ```rust,ignore
/// pub enum Context {
///     Test(Box<Test>),
///     Benchmark(Box<Benchmark>),
///     ExportJsonSchema(Box<ExportJsonSchema>),
/// }
/// ```
///
/// Variants are boxed to prevent enum size explosion when subcommands contain many
/// configurations.
///
/// ## 2. `Default` implementations
///
/// For subcommands that do not provide a hand-written `impl Default`, a default is
/// auto-generated by parsing empty CLI arguments:
///
/// ```rust,ignore
/// impl Default for ExportJsonSchema {
///     fn default() -> Self {
///         <Self as clap::Parser>::parse_from(std::iter::empty::<std::ffi::OsString>())
///     }
/// }
/// ```
///
/// If you provide your own `impl Default` inside the module, the macro detects it and skips
/// generation for that type.
///
/// ## 3. Compile-time safety
///
/// Inside a `const _: () = { ... }` block, the macro generates:
///
/// - A private `IsConfig` marker trait implemented for every `#[configuration]` type.
/// - A compile-time assertion that every field of every `#[subcommand]` struct is a type that
///   implements `IsConfig`. This catches mistakes like accidentally using a non-configuration
///   type as a subcommand field.
///
/// # Rules and constraints
///
/// - The module must have inline content (`mod context { ... }`), not a file reference
///   (`mod context;`).
/// - Every struct or enum in the module must be annotated with either `#[subcommand]` or
///   `#[configuration]`.
/// - `impl` blocks inside the module must target types defined within the same module (or the
///   context enum itself).
/// - A subcommand may have **at most one field** of each configuration type.
/// - Only `use` statements, structs, enums, and `impl` blocks are allowed inside the module.
#[proc_macro_attribute]
pub fn context(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let item = syn::parse_macro_input!(item as syn::ItemMod);
    match context::handler(attr.into(), item) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// Generates the runner-event reporting infrastructure from a grouped enum definition.
///
/// See `crates/report/src/runner_event.rs` for usage.
#[proc_macro]
pub fn define_runner_event(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    match runner_event::handler(input.into()) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}
