CONFIG_NAME: localnet
PRESET_BASE: mainnet

ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 0

TERMINAL_TOTAL_DIFFICULTY: 0

SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 14

MIN_GENESIS_TIME: 0
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 2048
GENESIS_DELAY: 0
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40

GENESIS_FORK_VERSION: 0x00000000
ALTAIR_FORK_VERSION: 0x01000000
BELLATRIX_FORK_VERSION: 0x02000000
CAPELLA_FORK_VERSION: 0x03000000
DENEB_FORK_VERSION: 0x04000000
ELECTRA_FORK_VERSION: 0x05000000

DEPOSIT_CHAIN_ID: 420420420
DEPOSIT_NETWORK_ID: 420420420
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000
