[package]
name = "revive-dt-profiler"
description = "Instrument and execute runtime Wasm to profile EVM opcodes"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
cumulus-primitives-proof-size-hostfunction = { workspace = true }
rustc-demangle = { workspace = true }
sc-executor = { workspace = true }
sp-core = { workspace = true }
sp-externalities = { workspace = true }
sp-io = { workspace = true }
sp-wasm-interface = { workspace = true }
sp-weights = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
parity-scale-codec = { workspace = true }
wat = { workspace = true }
